### ISSUE TITLE
Old files are not removed in the destination folder

### ISSUE THREAD

**Issue by cho-uc** [markwragg/PowerShell-HashCopy#9]
Hi,

I am using Copy-FileHash to copy files from _source_ folder to _destination_ folder.
However when the the _destination_ folder already contain files that do not exist in the _source_ folder, these files are not deleted.

I want to make sure that by the end of operation, both source and destination contain the same total number of files.
Can I achieve this this using Copy-FileHash without first clearing the _destination_ folder?

Thanks.

**Comment by markwragg** [comment]
Hi,

The `-Mirror` switch should do this. Per the example in the Readme:

> You can remove files from the Destination path that are not in the Source path by adding -Mirror:
> 
> Copy-FileHash -Path C:\Some\Files -Destination D:\Some\Other\Files -Mirror

**Comment by cho-uc** [comment]
Hello,

Ah I see, I miss it in the README.
It works now by adding `-Mirror`.

Another question: I noticed that you didn't mention `-Verbose` in the README.
May I know the reason why?
Thanks.

**Comment by markwragg** [comment]
I don't tend to explicitly document `-verbose` because its one of the default parameters that gets added when you author an advanced function by adding `[cmdletbinding()]`. As a result you should expect to find `-verbose` and `-debug` options on most tools and their behaviour is fairly standard.

**Comment by cho-uc** [comment]
Ah I see, it's clear now.
I will close this issue.

Thanks a lot! 😁
